document.writeln("<div class=\'head\'>");
document.writeln("        <div class=\'head_box\'>");
document.writeln("            <div class=\'logo\'>");
document.writeln("                <img src=\'img/logo.png\' alt=\'\'>");
document.writeln("                <p>");
document.writeln("                    <span>NAT（新加坡）基金会</span>");
document.writeln("                    <span>NAT FOUNDATION PTE.LTD.</span>");
document.writeln("                </p>");
document.writeln("            </div>");
document.writeln("            <ul>");
document.writeln("                <li class=\'select\'><a href=\'index.html\'>首页</a></li>");
document.writeln("                <li><a href=\'nat_economy.html\'>NAT生态经济体</a></li>");
document.writeln("                <li><a href=\'new_center.html\'>新闻中心</a></li>");
document.writeln("                <li><a href=\'strategy.html\'>战略规划</a></li>");
document.writeln("                <li><a href=\'scenarios.html\'>应用场景</a></li>");
document.writeln("                <li><a href=\'information.html\'>区块链信息</a></li>");
document.writeln("                <li><a href=\'technical.html\'>技术支持</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");